asia/urls.py
from django.urls import path
from asia.views import *

app_name = 'asia'

urlpatterns = [
    path('<slug>/', details_page_view, name="central-asia-detail"),
    # path('<slug>/', details_page_view, name="wedo-detail"),
    # path('opp/<slug>/', details_wedo_page_view, name="opportunities-detail"),
    # path('photo/', photo_bank_view, name="photo"),
]

consulting/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns

from infopages.views import *

admin.site.site_header = "Royal Consulting Admin"
admin.site.site_title = "Royal Consulting Admin Portal"
admin.site.index_title = "Welcome to Royal Consulting official web-site!"

urlpatterns = [
    path('', home_screen_view, name='home'),
    # path('home/', home_screen_view, name='home'),
    path('about/', AboutView.as_view(), name='about'),
    path('info/', include('infopages.urls', 'staticpages')),

    path('wedo/', include('wedo.urls', 'wedo')),
    path('central-asia/', include('asia.urls', 'asia')),
    path('competence/', include('competence.urls', 'competence')),
    path('admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
]

urlpatterns += i18n_patterns(

    path('info/', include('infopages.urls')),
    path('wedo/', include('wedo.urls')),
    path('central-asia/', include('asia.urls')),
    path('competence/', include('competence.urls')),
)


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

infopages/urls.py
from django.urls import path
from infopages.views import *

app_name = 'infopages'

urlpatterns = [
    path('about/', AboutView.as_view(), name='about'),
    path('news/', news_list_view, name='news-list'),
    path('news/<slug>/', detail_news_view, name="news-detail"),

    # path('coming/', ComingSoonView.as_view(), name='coming'),
    # path('faq/', FaqView.as_view(), name='faq'),
    # path('central-asia/', CentralAsiaView.as_view(), name='central-asia'),
    # path('resources-asia/', RerourcesView.as_view(), name='resources-asia'),
    # path('contact-us/', ContactsView.as_view(), name='contacts'),

    # path('story/<slug>/', individual_view, name="story-detail"),
]

wedo/urls.py
from django.urls import path
from wedo.views import *

app_name = 'wedo'

urlpatterns = [
    path('news-list/', news_list_view, name="news-list"),
    path('news-list/<slug>', news_detial_view, name="news-detail"),
    path('photo/', photo_bank_view, name="photo"),
    path('facts/', interesting_facts_page_view, name="facts"),
    path('statistics/', statistics_page_view, name="statistics"),
    path('publications/', statistics_page_view, name="publications"),
    path('<slug>/', details_page_view, name="wedo-detail"),
    path('opp/<slug>/', details_wedo_page_view, name="opportunities-detail"),
    # path('news-list/', news_list_view, name="news-list"),
    # path('photo/', photo_bank_view, name="photo"),
]

infopages/models.py
import os
from django.db import models
from django.db.models.signals import pre_save
from django.utils.text import slugify
from django.conf import settings
from django.db.models.signals import post_delete
from django.dispatch import receiver
from ckeditor.fields import RichTextField
from uuid import uuid4

import random as r


def upload_location(instance, filename):
    ext = filename.split('.')[-1]
    file_path = 'blog/{title}-{filename}'.format(
                title=str(instance.title), filename='{}.{}'.format(uuid4().hex, ext))
    return file_path

class NewsModel(models.Model):
    title = models.CharField(max_length=500, null=True, blank=True)
    body = RichTextField(null=True, blank=True)
    little_image = models.ImageField(upload_to=upload_location, null=True, blank=True)
    main_image = models.ImageField(upload_to=upload_location, null=True, blank=True)
    date_published = models.DateTimeField(auto_now_add=True, verbose_name="date published")
    slug = models.SlugField(blank=True, unique=True)


    class Meta:
        ordering = ['-date_published']
        verbose_name = 'News and Analytics'
        verbose_name_plural = 'News and Analytics'

    @property
    def imageURL(self):
        try:
            url = self.little_image.url
        except:
            url = ''
        return url

    @property
    def mainimageURL(self):
        try:
            url = self.main_image.url
        except:
            url = ''
        return url

    def __str__(self):
        return str(self.title)


















class InfoPageModel(models.Model):
    title = models.CharField(max_length=500, null=True, blank=True)
    pre_info = RichTextField(null=True, blank=True)
    body = RichTextField(null=True, blank=True)
    little_image = models.ImageField(upload_to=upload_location, null=True, blank=True)
    main_image = models.ImageField(upload_to=upload_location, null=True, blank=True)
    date_published = models.DateTimeField(auto_now_add=True, verbose_name="date published")
    slug = models.SlugField(blank=True, unique=True)

    class Meta:
        ordering = ['-date_published']
        verbose_name = 'Info page'
        verbose_name_plural = 'Info pages'

    @property
    def imageURL(self):
        try:
            url = self.little_image.url
        except:
            url = ''
        return url

    @property
    def mainimageURL(self):
        try:
            url = self.main_image.url
        except:
            url = ''
        return url

    def __str__(self):
        return str(self.title)





class IndustriesModel(models.Model):
    title = models.CharField(max_length=500, null=True, blank=True)
    body = RichTextField(null=True, blank=True)
    little_image = models.ImageField(upload_to=upload_location, null=True, blank=True)
    main_image = models.ImageField(upload_to=upload_location, null=True, blank=True)
    date_published = models.DateTimeField(auto_now_add=True, verbose_name="date published")
    slug = models.SlugField(blank=True, unique=True)

    class Meta:
        ordering = ['-date_published']

    @property
    def imageURL(self):
        try:
            url = self.little_image.url
        except:
            url = ''
        return url

    @property
    def mainimageURL(self):
        try:
            url = self.main_image.url
        except:
            url = ''
        return url

    def __str__(self):
        return str(self.title)





@receiver(post_delete, sender=NewsModel)
def submission_delete(sender, instance, **kwargs):
    instance.little_image.delete(False)
    instance.main_image.delete(False)



def pre_save_blog_post_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = slugify(str(r.randint(1,10000)) + "-" + str(r.randint(1,10000)))

pre_save.connect(pre_save_blog_post_receiver, sender=NewsModel)

def pre_save_infopage_post_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = slugify(str(r.randint(1,10000)) + "-" + str(r.randint(1,10000)))

pre_save.connect(pre_save_infopage_post_receiver, sender=InfoPageModel)

infopages/views.py
from django.shortcuts import render, redirect, get_object_or_404
from operator import attrgetter

from django.db.models import Q
from django.http import HttpResponse

from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator

from django.views.generic import TemplateView
from .models import NewsModel, InfoPageModel
from wedo.models import *
from asia.models import *
from django.utils.translation import ugettext_lazy as _

NEWS_PER_PAGE = 6

def home_screen_view(request, *args, **kwargs):

    wedo = InformationPagesModel.objects.all()
    asia = CentralAsiaPagesModel.objects.all()

    homenews = list(NewsModel.objects.all())[:4]
    context = {
        'wedo': wedo,
        'homenews': homenews,
        'asia': asia
    }

    return render(request, "pages/index.html", context)

def detail_news_view(request, slug):

    context = {}

    posts = get_object_or_404(NewsModel, slug=slug)
    context['posts'] = posts

    return render(request, 'pages/news_detail.html', context)






class ComingSoonView(TemplateView):
    template_name = 'pages/comingsoon.html'

class FaqView(TemplateView):
    template_name = 'pages/faq.html'

class HomeScreenView(TemplateView):
    template_name = 'pages/index.html'

class AboutView(TemplateView):
    template_name = 'pages/about.html'

class CentralAsiaView(TemplateView):
    template_name = 'pages/competence.html'

class RerourcesView(TemplateView):
    template_name = 'pages/recourses.html'

class ContactsView(TemplateView):
    template_name = 'pages/contacts.html'







def news_list_view(request, *args, **kwargs):
    context = {}

    query = ""
    query = request.GET.get('q', '')
    context['query'] = str(query)

    news = sorted(get_blog_queryset(query), key=attrgetter('date_published'), reverse=True)

    # Pagination
    page = request.GET.get('page', 1)
    news_paginator = Paginator(news, NEWS_PER_PAGE)

    try:
        news = news_paginator.page(page)
    except PageNotAnInteger:
        news = news_paginator.page(NEWS_PER_PAGE)
    except EmptyPage:
        news = news_paginator.page(news_paginator.num_pages)

    context['news'] = news

    return render(request, "pages/news_list.html", context)


def individual_view(request, slug):

    context = {}

    posts = get_object_or_404(InfoPageModel, slug=slug)
    context['posts'] = posts

    return render(request, 'pages/individual.html', context)



def get_blog_queryset(query=None):
    queryset = []
    queries = query.split(" ")
    for q in queries:
        news = NewsModel.objects.filter(
                Q(title__icontains=q) |
                Q(body__icontains=q)
            ).distinct()

        for new in news:
            queryset.append(new)

    return list(set(queryset))

infopages/templates/pages/about.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="container-fluid">
        <div class="row submenu">
            <div class="container">
                <div class="row">
                    <ul class="nav">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'infopages:about' %}">About</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'infopages:about' %}">Our Mission</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'infopages:about' %}">Our Team</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'wedo:wedo-detail' '9422-9099' %}">Capabilities</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'infopages:about' %}">Contacts</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12 p-0">
                <h5 class="page-title">About us</h5>
            </div>
        </div>
    </div>

    <div class="container about">
        <div class="row no-gutters mt-4">
            <p class="mt-4 main-text">
                Royal C - ведущий менеджер по глобальным инвестициям. Как новаторский инвестор в сфере воздействия,
                мы стремимся оказывать долгосрочное положительное влияние на сообщества и окружающую среду,
                обеспечивая при этом привлекательную прибыль для инвесторов.
                Наша цель - сделать эффективные инвестиционные решения доступными для всех и способствовать
                сознательному использованию капитала, приносящему пользу обществу и окружающей среде. Как
                профессиональный инвестиционный менеджер и эксперт в области инновационного смешанного
                финансирования, BlueOrchard является надежным партнером ведущих мировых финансовых институтов
                развития.
            </p>
            <div class="img my-4">
                <img src="{% static 'images/about.png' %}" alt="">

            </div>
            <p>
                С учётом сложившейся международной обстановки, консультация с широким активом, а также свежий взгляд
                на привычные вещи - безусловно открывает новые горизонты для инновационных методов управления
                процессами. В целом, конечно, сплочённость команды профессионалов обеспечивает актуальность
                поставленных обществом задач. Противоположная точка зрения подразумевает, что реплицированные с
                зарубежных источников, современные исследования освещают чрезвычайно интересные особенности картины
                в целом, однако конкретные выводы, разумеется, обнародованы. Высокотехнологичная концепция
                общественного уклада представляет собой интересный эксперимент проверки форм воздействия. Господа,
                высококачественный прототип будущего проекта прекрасно подходит для реализации существующих
                финансовых и административных условий. В рамках спецификации современных стандартов, стремящиеся
                вытеснить традиционное производство, нанотехнологии и по сей день остаются уделом либералов, которые
                жаждут быть указаны как претенденты на роль ключевых факторов.
            </p>
            <p>
                Являясь всего лишь частью общей картины, стремящиеся вытеснить традиционное производство,
                нанотехнологии освещают чрезвычайно интересные особенности картины в целом, однако конкретные
                выводы, разумеется, обнародованы. Есть над чем задуматься: независимые государства, которые
                представляют собой яркий пример континентально-европейского типа политической культуры, будут
                функционально разнесены на независимые элементы. Господа, глубокий уровень погружения создаёт
                предпосылки для дальнейших направлений развития. Господа, разбавленное изрядной долей эмпатии,
                рациональное мышление требует от нас анализа экспериментов, поражающих по своей масштабности и
                грандиозности.
            </p>
        </div>

        <div class="row my-3">
            <div class="col-lg-3 col-md-4 order-md-1 order-2 my-md-0 my-2">
                <img src="{% static 'images/mission1.png' %}" class="w-100 h-100" alt="">
            </div>
            <div class="col-lg-9 col-md-8 order-md-2 order-1">
                <div class="row">
                    <div class="col-lg-12">
                        <h2 class="big-title mt-4 mt-lg-1">Our mission</h2>
                        <p>
                            Taking into account the success rates, constant quantitative growth and the scope of our
                            activity is perfect for the implementation of innovative methods of process management. It's
                            nice, citizens, to see how the actions of the opposition representatives, overcoming the
                            current difficult economic situation, are associatively distributed among the sectors! There
                            is something to think about: conclusions drawn on the basis of Internet analytics are
                            gaining popularity among certain segments of the population, which means they must be
                            verified in a timely manner. Banal but irrefutable conclusions.
                        </p>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6 my-md-0 my-2"><img src="{% static 'images/mission2.png' %}" class="w-100 h-100" alt="">
                    </div>
                    <div class="col-md-6 my-md-0 my-2"><img src="{% static 'images/mission3.png' %}" class="w-100 h-100" alt="">
                    </div>
                </div>
            </div>
        </div>

        <div class="row my-5">
            <div class="col-lg-12">
                <h2 class="big-title">
                    Our team
                </h2>
                <div class="row mt-5">
                    <div class="col-lg-4">
                        <div class="team-member">
                            <h2>Gafur Gafurov </h2>
                            <p>Founder, President</p>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="team-member">
                            <h2>Elliot Smith </h2>
                            <p>Executive Director</p>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="team-member">
                            <h2>Sofia Johnson </h2>
                            <p>Legal and Business Affairs Director</p>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-4">
                        <div class="team-member">
                            <h2>Sabrina Brown </h2>
                            <p>Strategy and Finance Director</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>


{% endblock content %}

infopages/templates/pages/central-asia.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <section class="px-100 about">

        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12 p-0">
                    <h5 class="page-title">Geography and Traditions of Central Asia</h5>
                </div>
            </div>
        </div>

        <div class="container">
            <div class="row no-gutters mt-4">
                <p class="main-text">
                    &emsp;&emsp; Central Asia, broadly defined as the region east of the Caspian Sea incorporating
                    Kazakhstan,
                    Uzbekistan, Turkmenistan, Tajikistan, and Kyrgyzstan, has emerged as one world's fastest-growing regions
                    since the late 1990s and has shown
                    notable development potential. Among the region's advantages are its high-priced commodities (oil, gas,
                    cotton, and gold), reasonable
                    infrastructure and human capital, and a strategic location between Asia and Europe. Furthermore, Central
                    Asian regions have already
                    transitioned into market-oriented economic reforms to boost economic performance and private sector
                    competitiveness. These key characteristics
                    of countries have long been in the central interests of numerous developed countries to deepen economic
                    relations and develop
                    investment potential to expand trade turnover. <br>
                    &emsp;&emsp; The total area of the countries of the Central Asian regions is more than 4 million square
                    kilometers (see Figure). The northern part is
                    covered with Kazakhstan, which covers almost 68 percent of the entire territory. Kazakhstan bordered
                    Russia from the north, and half of the
                    western part stretches the Caspian Sea, from where it has direct sea access to Azerbaijan and Iran. <br>
                    &emsp;&emsp; The eastern part of Central Asia, consisting of Kazakhstan, Kyrgyzstan, and Tajikistan,
                    borders China. The total area of Kyrgyzstan is about
                    200 thousand square kilometers, whereas Tajikistan is 142 thousand square kilometers. The southern part
                    of Central Asian countries borders
                    most Turkmenistan between Iran, Uzbekistan, and Tajikistan to Afghanistan. The total area of Uzbekistan
                    is about 450 thousand square
                    kilometers, and Turkmenistan is more than 50 thousand square kilometers larger than Uzbekistan. <br>
                    There is no international sea access in these regions. This is significant for a region comprising
                    largely small landlocked economies with no
                    access to the sea for trade. Thanks to the recent joint efforts of the governments of these countries,
                    infrastructure is being developed and
                    expanded to build alternative routes of international logistics corridors with access to the sea for
                    closer countries bordering Central Asia, such
                    as Russia, China, Afghanistan, and Pakistan.
                </p>
                <div class="img">
                    <p class="bold">Figure. Central Asia overview</p>
                    <img src="{% static 'images/image.png' %}" alt="">
                    <span>Source: World Bank Data, updated statistics using BCG, Investing in Central Asia: One region, many
                        opportunities, 2018.</span>
                </div>
                <p class="main-text mt-4">
                    &emsp;&emsp; Traditions, culture, and language in Central Asia are very similar and, in many ways,
                    related. The Central Asian countries mostly share their religion of Islam. Strong respect for elders is
                    also common in Central Asia. People also attach great
                    importance to family and homeland. Under Soviet rule, people became dependent on sharing resources among
                    family members, which meant that a
                    strong extended family was valuable. <br>
                    &emsp;&emsp; Most of the population speaks their native language: Kazakh, Uzbek, Kyrgyz, Tajik and
                    Turkmen languages.
                    The peculiarity is that these languages are considered as the ancient Turkish and partly Persian
                    dialects. The influence of the
                    previous Soviet Union is an important factor in the culture of Central Asia. Russian is spoken in all
                    countries of Central Asia. After the collapse of
                    the Soviet Union, these countries focused on independent development policies, developed international
                    and diplomatic relations with almost all
                    countries. Consequently, young people focused on the study of foreign languages. Therefore, among the
                    younger generation of citizens,
                    knowledge of the English language has become much more popular.
                </p>
            </div>
        </div>

    </section>
{% endblock %}

infopages/templates/pages/individual.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <section class="px-100 about">
        <div class="row">
            <ul class="breadcrumb">
                <li class="breadcrumb-item"><a href="#">Home</a></li>
                <li class="breadcrumb-item"><a href="#">Tourism</a></li>
                <li class="breadcrumb-item active">{{ posts.title }}</li>
            </ul>
        </div>
        <div class="row animation">
            <div class="col-lg-12 animation_top">
                <h1 class="section-title">{{ posts.title }}</h1>
                <img src="{{posts.mainimageURL}}" class="w-100 mt-50" alt="">
            </div>
        </div>
        <div class="row align-items-center animation">
            <div class="col-lg-10 offset-lg-1 animation_left">
                <p class="mt-50">
                    {{ posts.body|safe }}
                </p>
            </div>
        </div>


    </section>
{% endblock %}

infopages/templates/pages/news_list.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% block content %}

    <section class="px-100">
        <div class="row">
            <ul class="breadcrumb">
                <li class="breadcrumb-item"><a href="#">Home</a></li>
                <li class="breadcrumb-item active">Blog</li>
            </ul>
        </div>

        <div class="row animation mt-4">
            <div class="col-lg-12 animation_top">
                <h1 class="section-title mb-lg-5 mb-3">Blog</h1>

                <div class="row mt-3">
                    {% for new in news %}
                        <div class="col-lg-4 col-md-6">
                            <div class="blog-item">
                                <img src="{{new.imageURL}}" alt="">
                                <div class="blog-caption">
                                    <h6>{{new.title}}</h6>
                                    <p>{{new.body|safe|truncatechars:180}}</p>
                                    <a href="{% url 'infopages:news-detail' new.slug %}" class="more-btn">More</a>
                                </div>
                            </div>
                        </div>
                    {% endfor %}

{#                    <div class="col-lg-4 col-md-6">#}
{#                        <div class="blog-item">#}
{#                            <img src="data/images/blog1.png" alt="">#}
{#                            <div class="blog-caption">#}
{#                                <h6>Our victory was accompanied by the voice of the coming generation</h6>#}
{#                                <p>By the way, thorough competitor research is gaining popularity ...</p>#}
{#                                <a href="" class="more-btn">More</a>#}
{#                            </div>#}
{#                        </div>#}
{#                    </div>#}
{#                    <div class="col-lg-4 col-md-6">#}
{#                        <div class="blog-item">#}
{#                            <img src="data/images/blog2.png" alt="">#}
{#                            <div class="blog-caption">#}
{#                                <h6>Speakers of the State Duma chamber are indignant</h6>#}
{#                                <p>It should be noted that the modern development methodology speaks about the#}
{#                                    capabilities of the system ...</p>#}
{#                                <a href="" class="more-btn">More</a>#}
{#                            </div>#}
{#                        </div>#}
{#                    </div>#}
{#                    <div class="col-lg-4 col-md-6">#}
{#                        <div class="blog-item">#}
{#                            <img src="data/images/blog3.png" alt="">#}
{#                            <div class="blog-caption">#}
{#                                <h6>Noble aspirations will not save: the sky darkens</h6>#}
{#                                <p>As part of the big picture, emerging economies ...</p>#}
{#                                <a href="" class="more-btn">More</a>#}
{#                            </div>#}
{#                        </div>#}
{#                    </div>#}
{#                    <div class="col-lg-4 col-md-6">#}
{#                        <div class="blog-item">#}
{#                            <img src="data/images/blog4.png" alt="">#}
{#                            <div class="blog-caption">#}
{#                                <h6>A trifle, but nice: the young growth grows older</h6>#}
{#                                <p>A course towards a socially oriented national project ...</p>#}
{#                                <a href="" class="more-btn">More</a>#}
{#                            </div>#}
{#                        </div>#}
{#                    </div>#}
{#                    <div class="col-lg-4 col-md-6">#}
{#                        <div class="blog-item">#}
{#                            <img src="data/images/blog3.png" alt="">#}
{#                            <div class="blog-caption">#}
{#                                <h6>Noble aspirations will not save: the sky darkens</h6>#}
{#                                <p>As part of the big picture, emerging economies ...</p>#}
{#                                <a href="" class="more-btn">More</a>#}
{#                            </div>#}
{#                        </div>#}
{#                    </div>#}
{#                    <div class="col-lg-4 col-md-6">#}
{#                        <div class="blog-item">#}
{#                            <img src="data/images/blog4.png" alt="">#}
{#                            <div class="blog-caption">#}
{#                                <h6>A trifle, but nice: the young growth grows older</h6>#}
{#                                <p>A course towards a socially oriented national project ...</p>#}
{#                                <a href="" class="more-btn">More</a>#}
{#                            </div>#}
{#                        </div>#}
{#                    </div>#}
                </div>
                <div class="row mt-4">
                    <div class="col-lg-12">
                        <ul class="pagination-lg pagination justify-content-end">
                            {% if news.has_previous %}
                                <li class="page-item">
                                  <a class="page-link" href="?{% if query %}q={{query}}&{% endif %}page={{ news.previous_page_number }}">&laquo;</a>
                                </li>
                            {% endif %}


                            {% for i in news.paginator.page_range %}
                                {% if news.number == i %}
                                    <li class="page-item active"><a class="page-link">{{ i }}</a></li>
                                {% else %}
                                    <li class="page-item" ><a class="page-link" href="?{% if query %}q={{query}}&{% endif %}page={{ i }}">{{ i }}</a></li>
                                {% endif %}
                            {% endfor %}

                            {% if blog_posts.has_next %}
                                <li class="page-item">
                                  <a class="page-link" href="?{% if query %}q={{query}}&{% endif %}page={{ news.next_page_number }}">Next</a>
                                </li>
                                <li class="page-item">
                                  <a class="page-link"  href="?{% if query %}q={{query}}&{% endif %}page={{ news.paginator.num_pages }}">Last &raquo;</a>
                                </li>
                            {% endif %}
{#                    <div class="col-lg-12">#}
{#                        <ul class="pagination-lg pagination justify-content-end">#}
{#                            <li class="page-item"><a class="page-link" href="#">&laquo;</a></li>#}
{#                            <li class="page-item active"><a class="page-link" href="#">1</a></li>#}
{#                            <li class="page-item"><a class="page-link" href="#">2</a></li>#}
{#                            <li class="page-item"><a class="page-link" href="#">3</a></li>#}
{#                            <li class="page-item"><a class="page-link" href="#">&raquo;</a></li>#}
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </section>

{% endblock %}