asia/urls.py
from django.urls import path
from asia.views import *

app_name = 'asia'

urlpatterns = [
    path('<slug>/', details_page_view, name="central-asia-detail"),
    # path('<slug>/', details_page_view, name="wedo-detail"),
    # path('opp/<slug>/', details_wedo_page_view, name="opportunities-detail"),
    # path('photo/', photo_bank_view, name="photo"),
]

consulting/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns

from infopages.views import *

admin.site.site_header = "Royal Consulting Admin"
admin.site.site_title = "Royal Consulting Admin Portal"
admin.site.index_title = "Welcome to Royal Consulting official web-site!"

urlpatterns = [
    path('', home_screen_view, name='home'),
    # path('home/', home_screen_view, name='home'),
    path('about/', AboutView.as_view(), name='about'),
    path('info/', include('infopages.urls', 'staticpages')),

    path('wedo/', include('wedo.urls', 'wedo')),
    path('central-asia/', include('asia.urls', 'asia')),
    path('competence/', include('competence.urls', 'competence')),
    path('admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
]

urlpatterns += i18n_patterns(

    path('info/', include('infopages.urls')),
    path('wedo/', include('wedo.urls')),
    path('central-asia/', include('asia.urls')),
    path('competence/', include('competence.urls')),
)


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

wedo/urls.py
from django.urls import path
from wedo.views import *

app_name = 'wedo'

urlpatterns = [
    path('news-list/', news_list_view, name="news-list"),
    path('news-list/<slug>', news_detial_view, name="news-detail"),
    path('photo/', photo_bank_view, name="photo"),
    path('facts/', interesting_facts_page_view, name="facts"),
    path('statistics/', statistics_page_view, name="statistics"),
    path('publications/', statistics_page_view, name="publications"),
    path('<slug>/', details_page_view, name="wedo-detail"),
    path('opp/<slug>/', details_wedo_page_view, name="opportunities-detail"),
    # path('news-list/', news_list_view, name="news-list"),
    # path('photo/', photo_bank_view, name="photo"),
]

wedo/models.py
from django.db import models
from ckeditor.fields import RichTextField
from django.db.models.signals import pre_save
from django.utils.text import slugify
from django.dispatch import receiver
from django.db.models.signals import post_delete
from uuid import uuid4


import random as r

def upload_location(instance, filename):
    ext = filename.split('.')[-1]
    file_path = 'wedo/{title}-{filename}'.format(
                title=str(instance.title), filename='{}.{}'.format(uuid4().hex, ext))
    return file_path


class InformationPagesModel(models.Model):
    title = models.CharField(max_length=500, null=True, blank=True)
    body = RichTextField(null=True, blank=True)
    image = models.ImageField(upload_to=upload_location, null=True, blank=True)
    date_published = models.DateTimeField(auto_now_add=True, verbose_name="date published")
    slug = models.SlugField(blank=True, unique=True)

    class Meta:
        ordering = ['-date_published']
        verbose_name = 'What are we doing?'
        verbose_name_plural = 'What are we doing?'


    @property
    def imageURL(self):
        try:
            url = self.image.url
        except:
            url = ''
        return url

    def __str__(self):
        return str(self.title)



class OpportunitiesModel(models.Model):
    title = models.CharField(max_length=500, null=True, blank=True)
    body = RichTextField(null=True, blank=True)
    image = models.ImageField(upload_to=upload_location, null=True, blank=True)
    date_published = models.DateTimeField(auto_now_add=True, verbose_name="date published")
    slug = models.SlugField(blank=True, unique=True)

    class Meta:
        ordering = ['-date_published']
        verbose_name = 'Business Opportunities'

    @property
    def imageURL(self):
        try:
            url = self.image.url
        except:
            url = ''
        return url

    def __str__(self):
        return str(self.title)


class PhotoBankModel(models.Model):
    title = models.CharField(max_length=500, null=True, blank=True)
    image = models.ImageField(upload_to=upload_location, null=True, blank=True)
    date_published = models.DateTimeField(auto_now_add=True, verbose_name="date published")
    slug = models.SlugField(blank=True, unique=True)

    class Meta:
        ordering = ['-date_published']
        verbose_name = 'Photo bank'

    @property
    def imageURL(self):
        try:
            url = self.image.url
        except:
            url = ''
        return str(url)

    def __str__(self):
        return str(self.title)


R_A_CHOICES = [
    ('News and Analytics', 'News and Analytics'),
    ('Interesting facts', 'Interesting facts'),
    ('Data and Statistics', 'Data and Statistics'),
    ('Publications', 'Publications'),
]


class NewsModel(models.Model):
    title = models.CharField(max_length=500, null=True, blank=True)
    body = RichTextField(null=True, blank=True)
    image = models.ImageField(upload_to=upload_location, null=True, blank=True)
    date_published = models.DateTimeField(auto_now_add=True, verbose_name="date published")
    slug = models.SlugField(blank=True, unique=True)
    category = models.CharField(
        max_length=50,
        choices=R_A_CHOICES,
        default='News and Analytics',
    )


    class Meta:
        ordering = ['-date_published']
        verbose_name = 'News and Analytics'
        verbose_name_plural = 'News and Analytics'

    @property
    def imageURL(self):
        try:
            url = self.image.url
        except:
            url = ''
        return url

    def __str__(self):
        return str(self.title)


@receiver(post_delete, sender=InformationPagesModel)
@receiver(post_delete, sender=OpportunitiesModel)
@receiver(post_delete, sender=NewsModel)
def submission_delete(sender, instance, **kwargs):
    instance.image.delete(False)

def pre_save_post_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = slugify(str(r.randint(1,10000)) + "-" + str(r.randint(1,10000)))
pre_save.connect(pre_save_post_receiver, sender=InformationPagesModel)


def pre_save_opportunities_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = slugify(str(r.randint(1,10000)) + "-" + str(r.randint(1,10000)))
pre_save.connect(pre_save_post_receiver, sender=OpportunitiesModel)


def pre_save_photo_bank_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = slugify(str(r.randint(1,10000)) + "-" + str(r.randint(1,10000)))
pre_save.connect(pre_save_photo_bank_receiver, sender=PhotoBankModel)


def pre_save_news_bank_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = slugify(str(r.randint(1,10000)) + "-" + str(r.randint(1,10000)))
pre_save.connect(pre_save_news_bank_receiver, sender=NewsModel)

wedo/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.db.models import Q
from operator import attrgetter
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from .models import *

NEWS_PER_PAGE = 12


def news_detial_view(request, slug):

    context = {}
    pages = OpportunitiesModel.objects.all()
    posts = get_object_or_404(NewsModel, slug=slug)
    context = {
        'posts': posts,
        'pages': pages,
    }

    return render(request, 'details_page.html', context)



def photo_bank_view(request, *args, **kwargs):

    context = {}

    photos = PhotoBankModel.objects.all()
    context['photos'] = photos

    return render(request, 'photo_bank.html', context)


def details_page_view(request, slug):

    context = {}
    pages = InformationPagesModel.objects.all()

    posts = get_object_or_404(InformationPagesModel, slug=slug)
    # context['posts'] = posts
    context = {
        'posts': posts,
        'pages': pages,
    }

    return render(request, 'details_page.html', context)


def details_wedo_page_view(request, slug):

    context = {}
    pages = OpportunitiesModel.objects.all()
    posts = get_object_or_404(OpportunitiesModel, slug=slug)
    context = {
        'posts': posts,
        'pages': pages,
    }

    return render(request, 'opp_details_page.html', context)


def interesting_facts_page_view(request):

    context = {}
    facts = NewsModel.objects.filter(category='Interesting facts')
    context = {
        'facts': facts,
    }

    return render(request, 'template_page.html', context)


def statistics_page_view(request):

    context = {}
    facts = NewsModel.objects.filter(category='Data and Statistics')
    context = {
        'facts': facts,
    }

    return render(request, 'statistics_page.html', context)


def publications_page_view(request):

    context = {}
    facts = NewsModel.objects.filter(category='Publications')
    context = {
        'facts': facts,
    }

    return render(request, 'publications.html', context)



def news_page_view(request, slug):

    context = {}
    pages = OpportunitiesModel.objects.all()
    posts = get_object_or_404(OpportunitiesModel, slug=slug)
    context = {
        'posts': posts,
        'pages': pages,
    }

    return render(request, 'opp_details_page.html', context)


# def news_detial_view(request, slug):
#
#     context = {}
#     pages = OpportunitiesModel.objects.all()
#     posts = get_object_or_404(NewsModel, slug=slug)
#     context = {
#         'posts': posts,
#         'pages': pages,
#     }
#
#     return render(request, 'details_page.html', context)


def news_list_view(request, *args, **kwargs):
    context = {}

    query = ""
    query = request.GET.get('q', '')
    context['query'] = str(query)

    news = sorted(get_news_queryset(query), key=attrgetter('date_published'), reverse=True)

    # Pagination
    page = request.GET.get('page', 1)
    news_paginator = Paginator(news, NEWS_PER_PAGE)

    try:
        news = news_paginator.page(page)
    except PageNotAnInteger:
        news = news_paginator.page(NEWS_PER_PAGE)
    except EmptyPage:
        news = news_paginator.page(news_paginator.num_pages)

    context['news'] = news

    return render(request, "news.html", context)



def get_news_queryset(query=None):
    news_queryset = []

    queries = query.split(" ")
    for q in queries:
        news = NewsModel.objects.filter(
                Q(title__icontains=q) |
                Q(body__icontains=q)
            ).distinct()

        for new in news:
            news_queryset.append(new)

    return list(set(news_queryset))

wedo/templates/details_page.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% block content %}
    <div class="container-fluid">
        <div class="row submenu">
            <div class="container">
                <div class="row">
                    <ul class="nav">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'wedo:news-list' %}">News and Analytics</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Interesting facts</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Data and statistics</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Recent Publications</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12 p-0">
                <h5 class="page-title">{{ posts.title }}</h5>
            </div>
        </div>
    </div>

    <div class="container">
        <div class="row no-gutters mt-4">
            <div class="img w-100">
                <img src="{{posts.imageURL}}" alt="">
                <span>{{ posts.imageSource }}</span>
            </div>

            <p class="main-text">
                {{ posts.body|safe }}
            </p>

        </div>
    </div>









{% endblock %}

wedo/templates/news.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% block content %}
<!-- subnavbar -->
<div class="container-fluid">
    <div class="row submenu">
        <div class="container">
            <div class="row">
                <ul class="nav">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'wedo:news-list' %}">News and Analytics</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Interesting facts</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Data and statistics</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Recent Publications</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col-12">
            <h3 class="big-title mt-5">News</h3>
        </div>
    </div>

    <div class="row animation news mt-3">
        {% for anews in news %}
            <div class="col-md-4 animation_left">
                <a href="{% url 'wedo:news-detail' anews.slug %}">
{#                <a href="">#}
                    <img src="{{ anews.imageURL }}" class="w-100" alt="">
                    <p class="mt-3">{{ anews.date_published}}</p>
                    <p class="bold">{{ anews.title}}</p>
                </a>
            </div>
        {% endfor %}

    </div>
    <div class="row mt-5">
        <div class="col-12">
            <ul class="pagination justify-content-end">
                {% if news.has_previous %}
                    <li class="page-item">
                      <a class="page-link" href="?{% if query %}q={{query}}&{% endif %}page={{ news.previous_page_number }}">&laquo;</a>
                    </li>
                {% endif %}


                {% for i in news.paginator.page_range %}
                    {% if news.number == i %}
                        <li class="page-item active"><a class="page-link">{{ i }}</a></li>
                    {% else %}
                        <li class="page-item" ><a class="page-link" href="?{% if query %}q={{query}}&{% endif %}page={{ i }}">{{ i }}</a></li>
                    {% endif %}
                {% endfor %}

                {% if blog_posts.has_next %}
                    <li class="page-item">
                      <a class="page-link" href="?{% if query %}q={{query}}&{% endif %}page={{ news.next_page_number }}">Next</a>
                    </li>
                    <li class="page-item">
                      <a class="page-link"  href="?{% if query %}q={{query}}&{% endif %}page={{ news.paginator.num_pages }}">Last &raquo;</a>
                    </li>
                {% endif %}
{#                <li class="page-item"><a class="page-link" href="#">Previous</a></li>#}
{#                <li class="page-item"><a class="page-link" href="#">1</a></li>#}
{#                <li class="page-item active"><a class="page-link" href="#">2</a></li>#}
{#                <li class="page-item"><a class="page-link" href="#">3</a></li>#}
{#                <li class="page-item"><a class="page-link" href="#">Next</a></li>#}
            </ul>
        </div>
    </div>
</div>

{% endblock %}

wedo/templates/opp_details_page.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% block content %}
    <div class="container-fluid">
        <div class="row submenu">
            <div class="container">
                <div class="row">
                    <ul class="nav">

                        {% for page in pages %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'wedo:opportunities-detail' page.slug %}">{{ page.title }}</a>
                            </li>
                        {% endfor %}

                    </ul>
                </div>
            </div>
        </div>
    </div>

    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12 p-0">
                <h5 class="page-title">{{ posts.title }}</h5>
            </div>
        </div>
    </div>

    <div class="container">
        <div class="row no-gutters mt-4">
            <div class="img w-100">
{#                <p class="bold">Figure. Central Asia overview</p>#}
                <img src="{{posts.imageURL}}" alt="">
                <span>{{ posts.imageSource }}</span>
            </div>

            <p class="main-text">
                {{ posts.body|safe }}
            </p>

        </div>
    </div>









{% endblock %}

wedo/templates/photo_bank.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% block content %}
    <div class="container-fluid">
        <div class="row submenu">
            <div class="container">
                <div class="row">
                    <ul class="nav">
                        <li class="nav-item">
                            <a class="nav-link" href="#">Geography</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Economics</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Central Asian Republics</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12 p-0">
                <h5 class="page-title">Photo bank</h5>
            </div>
        </div>
    </div>

    <div class="container">
        <div class="row no-gutters mt-4">
            {% for photo in photos %}
                <p class="page-title">
                    {{ photo.title }}
                </p>
                <div class="img w-100">
                    <img src="{{photo.imageURL}}" alt="">
                    <span>{{ photo.imageURL }}</span>
                </div>


            {% endfor %}


        </div>
    </div>









{% endblock %}

wedo/templates/publications.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% block content %}
<!-- subnavbar -->
<div class="container-fluid">
    <div class="row submenu">
        <div class="container">
            <div class="row">
                <ul class="nav">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'wedo:news-list' %}">News and Analytics</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'wedo:facts' %}">Interesting facts</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'wedo:statistics' %}">Data and statistics</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'wedo:publications' %}">Recent Publications</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col-12">
            <h3 class="big-title mt-5">Recent Publications</h3>
        </div>
    </div>

    <div class="row animation news mt-3">
        {% for fact in facts %}
            <div class="col-md-4 animation_left">
                <a href="{% url 'wedo:news-detail' fact.slug %}">
{#                <a href="">#}
                    <img src="{{ fact.imageURL }}" class="w-100" alt="">
                    <p class="mt-3">{{ fact.date_published}}</p>
                    <p class="bold">{{ fact.title}}</p>
                </a>
            </div>
        {% endfor %}

    </div>

</div>

{% endblock %}

wedo/templates/statistics_page.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% block content %}
<!-- subnavbar -->
<div class="container-fluid">
    <div class="row submenu">
        <div class="container">
            <div class="row">
                <ul class="nav">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'wedo:news-list' %}">News and Analytics</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'wedo:facts' %}">Interesting facts</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'wedo:statistics' %}">Data and statistics</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'wedo:publications' %}">Recent Publications</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col-12">
            <h3 class="big-title mt-5">Data and Statistics</h3>
        </div>
    </div>

    <div class="row animation news mt-3">
        {% for fact in facts %}
            <div class="col-md-4 animation_left">
                <a href="{% url 'wedo:news-detail' fact.slug %}">
{#                <a href="">#}
                    <img src="{{ fact.imageURL }}" class="w-100" alt="">
                    <p class="mt-3">{{ fact.date_published}}</p>
                    <p class="bold">{{ fact.title}}</p>
                </a>
            </div>
        {% endfor %}

    </div>

</div>

{% endblock %}

wedo/templates/template_page.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% block content %}
<!-- subnavbar -->
<div class="container-fluid">
    <div class="row submenu">
        <div class="container">
            <div class="row">
                <ul class="nav">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'wedo:news-list' %}">News and Analytics</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'wedo:facts' %}">Interesting facts</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'wedo:statistics' %}">Data and statistics</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'wedo:publications' %}">Recent Publications</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col-12">
            <h3 class="big-title mt-5">Interesting facts</h3>
        </div>
    </div>

    <div class="row animation news mt-3">
        {% for fact in facts %}
            <div class="col-md-4 animation_left">
                <a href="{% url 'wedo:news-detail' fact.slug %}">
{#                <a href="">#}
                    <img src="{{ fact.imageURL }}" class="w-100" alt="">
                    <p class="mt-3">{{ fact.date_published}}</p>
                    <p class="bold">{{ fact.title}}</p>
                </a>
            </div>
        {% endfor %}

    </div>

</div>

{% endblock %}