asia/urls.py
from django.urls import path
from asia.views import *

app_name = 'asia'

urlpatterns = [
    path('<slug>/', details_page_view, name="central-asia-detail"),
    # path('<slug>/', details_page_view, name="wedo-detail"),
    # path('opp/<slug>/', details_wedo_page_view, name="opportunities-detail"),
    # path('photo/', photo_bank_view, name="photo"),
]

competence/urls.py
from django.urls import path
from competence.views import *

app_name = 'competence'

urlpatterns = [
    path('about/', AboutView.as_view(), name="about"),
    path('contact/', ContactView.as_view(), name="contact"),
    path('contact-us/', contact_us_view, name="contact-us"),
    path('<slug>/', details_page_view, name="competence-detail"),
]

consulting/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns

from infopages.views import *

admin.site.site_header = "Royal Consulting Admin"
admin.site.site_title = "Royal Consulting Admin Portal"
admin.site.index_title = "Welcome to Royal Consulting official web-site!"

urlpatterns = [
    path('', home_screen_view, name='home'),
    # path('home/', home_screen_view, name='home'),
    path('about/', AboutView.as_view(), name='about'),
    path('info/', include('infopages.urls', 'staticpages')),

    path('wedo/', include('wedo.urls', 'wedo')),
    path('central-asia/', include('asia.urls', 'asia')),
    path('competence/', include('competence.urls', 'competence')),
    path('admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
]

urlpatterns += i18n_patterns(

    path('info/', include('infopages.urls')),
    path('wedo/', include('wedo.urls')),
    path('central-asia/', include('asia.urls')),
    path('competence/', include('competence.urls')),
)


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

wedo/urls.py
from django.urls import path
from wedo.views import *

app_name = 'wedo'

urlpatterns = [
    path('news-list/', news_list_view, name="news-list"),
    path('news-list/<slug>', news_detial_view, name="news-detail"),
    path('photo/', photo_bank_view, name="photo"),
    path('facts/', interesting_facts_page_view, name="facts"),
    path('statistics/', statistics_page_view, name="statistics"),
    path('publications/', statistics_page_view, name="publications"),
    path('<slug>/', details_page_view, name="wedo-detail"),
    path('opp/<slug>/', details_wedo_page_view, name="opportunities-detail"),
    # path('news-list/', news_list_view, name="news-list"),
    # path('photo/', photo_bank_view, name="photo"),
]

templates/snippets/footer.html
{% load static %}
{% load i18n %}
{#<div class="footer px-100 mt-100">#}
{#    <div class="container-fluid">#}
{#        <div class="row">#}
{#            <div class="col-lg-3">#}
{#                <img src="{% static 'images/logo-white.png' %}" class="logo" alt="">#}
{#                <ul class="nav mt-4">#}
{#                    <li class="nav-item">#}
{#                        <a class="nav-link" href="#"><img src="{% static 'images/facebook.png' %}" alt=""></a>#}
{#                    </li>#}
{#                    <li class="nav-item">#}
{#                        <a class="nav-link" href="#"><img src="{% static 'images/instagram.png' %}" alt=""></a>#}
{#                    </li>#}
{#                    <li class="nav-item">#}
{#                        <a class="nav-link" href="#"><img src="{% static 'images/twitter.png' %}" alt=""></a>#}
{#                    </li>#}
{#                    <li class="nav-item">#}
{#                        <a class="nav-link" href="#"><img src="{% static 'images/telegram.png' %}" alt=""></a>#}
{#                    </li>#}
{#                </ul>#}
{#            </div>#}
{#            <div class="col-lg-2">#}
{#                <h6>Useful links</h6>#}
{#                <ul class="nav flex-column">#}
{#                    <li class="nav-item">#}
{#                        <a class="nav-link" href="{% url 'investors:investor-index' %}">Investor</a>#}
{#                    </li>#}
{#                    <li class="nav-item">#}
{#                        <a class="nav-link" href="{% url 'entrepreneurs:entrepreneur-index' %}">Entrepreneur</a>#}
{#                    </li>#}
{#                    <li class="nav-item">#}
{#                        <a class="nav-link" href="{% url 'staticpages:about' %}">About us</a>#}
{#                    </li>#}
{#                    <li class="nav-item">#}
{#                        <a class="nav-link" href="{% url 'staticpages:news-list' %}">News</a>#}
{#                    </li>#}
{#                    <li class="nav-item">#}
{#                        <a class="nav-link" href="{% url 'staticpages:faq' %}">FAQ</a>#}
{#                    </li>#}
{#                    <li class="nav-item">#}
{#                        <a class="nav-link" href="{% url 'staticpages:contacts' %}">Contacts</a>#}
{#                    </li>#}
{#                </ul>#}
{#            </div>#}
{#            <div class="col-lg-3">#}
{#                <h6>Contacts</h6>#}
{#                <p class="mb-1">Address: Uzbekistan, Tashkent, st. Katta-Hirmontepa, 1, 1000002</p>#}
{#                <p><a href="" class="nav-link">E-mail: info@royalco.com</a></p>#}
{#                <p><a href="" class="nav-link">Phone: +99 899 999-99-99</a></p>#}
{#                <p><a href="" class="nav-link">Working days: Mon. - Sat: 9:00 to 18:00</a></p>#}
{#            </div>#}
{#            <div class="col-lg-4">#}
{#                <h6>Get in touch</h6>#}
{#                <form action="">#}
{#                    <div class="row">#}
{#                        <div class="col-lg-12">#}
{#                            <input type="text" placeholder="Name">#}
{#                            <input type="text" placeholder="Phone number">#}
{#                            <input type="text" placeholder="Message">#}
{#                        </div>#}
{#                    </div>#}
{#                    <button class="active-btn" type="submit">Send</button>#}
{#                </form>#}
{#            </div>#}
{#        </div>#}
{#    </div>#}
{#</div>#}



<hr class="mb-0">
    <div class="container py-2 social-networks">
        <div class="row align-items-center">
            <div class="col-lg-3 text-lg-left text-center">
                <p class="m-0 bold">We are on social networks </p>
                <p class="m-0 bold">Follow and subscribe to us:</p>
            </div>
            <div class="col-lg-9">
                <div class="container-fluid p-0">
                    <div class="row mt-3 mt-lg-0">
                        <div class="col-md-3">
                            <a href="https://twitter.com/RoyalConsultin2">
                                <img src="{% static 'images/twitter.svg'%}" alt="">
                                <span>Twitter</span>
                            </a>
                        </div>
                        <div class="col-md-3">
                            <a href="https://www.facebook.com/royalconsultinginc">
                                <img src="{% static 'images/facebook.svg'%}" alt="">
                                <span>Facebook</span>
                            </a>
                        </div>
                        <div class="col-md-3">
                            <a href="https://www.linkedin.com/company/77359142/admin/">
                                <img src="{% static 'images/linkedin.svg'%}" alt="">
                                <span>LinkedIn</span>
                            </a>
                        </div>
                        <div class="col-md-3">
                            <a href="https://www.instagram.com/royalconsultinginc/">
                                <img src="{% static 'images/instagram.svg'%}" alt="">
                                <span>Instagram</span>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="footer">
        <div class="container">
            <div class="row">
                <div class="col-lg-4">
                    <img src="{% static 'images/logo.png' %}" class="footer-logo" alt="footer-logo">
                    <h5 class="bold my-4">Royal Consulting Inc.</h5>
                    <p class="bold">
                        © 2021 Official website of Royal Consulting Inc.
                        All rights reserved.
                    </p>
                    <p class="bold">
                        Note: If you find an error in the text,
                        select it and press Ctrl + Enter to notify us.
                    </p>
                </div>
                <div class="col-lg-8">
                    <div class="container-fluid d-flex h-100 justify-content-between flex-column">
                        <div class="row footer-address pl-4">
                            <div class="col-md-6">
                                <h5 class="bold">
                                    Richmond Office (USA)
                                </h5>
                                <p class="mt-3">
                                    12833 Church Rd
                                    Henrico, VA 23233
                                </p>
                            </div>
                            <div class="col-md-6">
                                <h5 class="bold">
                                    Tashkent Office (Uzbekistan)
                                </h5>
                                <p class="mt-3">
                                    35, Beruniy Str., Shaykhantahur,
                                    Tashkent, Uzbekistan
                                </p>
                            </div>
                        </div>

                        <div class="row footer-phone pl-4">
                            <div class="col-md-6">
                                <h5 class="bold">
                                    +1 (804) 492 00 27, <br>
                                    +1 (475) 473 50 50
                                </h5>
                            </div>
                            <div class="col-md-6">
                                <h5 class="bold">
                                    +998 (93) 541 48 23
                                </h5>
                            </div>
                        </div>

                        <div class="row footer-mail pl-4">
                            <div class="col-md-6">
                                <h5 class="bold">
                                    info@royalc.us
                                </h5>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>

templates/snippets/header.html
{% load static %}
{% load i18n %}


<div class="container">
    <div class="row">
        <nav class="navbar navbar-expand-lg w-100">
            <!-- Brand -->
            <a class="navbar-brand" href="{% url 'home' %}"><img src="{% static 'images/logo.png'%}" alt="logo"></a>

            <!-- Toggler/collapsibe Button -->
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
                <svg width="29" height="29" viewBox="0 0 29 29" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path d="M5.59888 14.2008H23.5989M5.59888 8.20081H23.5989M5.59888 20.2008H23.5989"
                        stroke="#1D3B70" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />
                </svg>

            </button>

            <!-- Navbar links -->
            <div class="collapse navbar-collapse" id="collapsibleNavbar">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <div class="dropdown">
                            <a type="button" class="nav-link" data-toggle="dropdown">
                                Central Asia
                            </a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" href="{% url 'asia:central-asia-detail' '1478-6270' %}">Geography</a>
                                <a class="dropdown-item" href="{% url 'asia:central-asia-detail' '6986-5741' %}">Economics</a>
                                <a class="dropdown-item" href="{% url 'asia:central-asia-detail' '5951-7651' %}">Central Asian Republics </a>
                            </div>
                        </div>
                    </li>
                    <li class="nav-item">
                        <div class="dropdown">
                            <a type="button" class="nav-link" data-toggle="dropdown">
                                Competence
                            </a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" href="{% url 'competence:competence-detail' '4811-1353' %}">About Us</a>
                                <a class="dropdown-item" href="{% url 'competence:competence-detail' '4811-1353' %}">Our mission</a>
                                <a class="dropdown-item" href="{% url 'competence:competence-detail' '4811-1353' %}">Our team</a>
                                <a class="dropdown-item" href="{% url 'competence:competence-detail' '4290-1299' %}">Capabilities</a>
                                <a class="dropdown-item" href="{% url 'competence:contact-us' %}">Contacts </a>
                            </div>
                        </div>
                    </li>
                    <li class="nav-item">
                        <div class="dropdown">
                            <a type="button" class="nav-link" data-toggle="dropdown">
                                What are we doing?
                            </a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" href="{% url 'wedo:wedo-detail' '4225-1191' %}">Partnership cooperation</a>
                                <a class="dropdown-item" href="{% url 'wedo:wedo-detail' '113-9541' %}">Investor expectations</a>
                            </div>


                        </div>
                    </li>
                    <li class="nav-item">
                        <div class="dropdown">
                            <a type="button" class="nav-link" data-toggle="dropdown">
                                Business Opportunities
                            </a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" href="{% url 'wedo:opportunities-detail' '2491-8824' %}">Discover Industries</a>
                                <a class="dropdown-item" href="{% url 'wedo:opportunities-detail' '4746-2778' %}">Market Analysis</a>
                            </div>
                        </div>
                    </li>
                    <li class="nav-item">
                        <div class="dropdown">
                            <a type="button" class="nav-link" data-toggle="dropdown">
                                Research and Analytics
                            </a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" href="{% url 'wedo:news-list' %}">News and analytics </a>
                                <a class="dropdown-item" href="{% url 'wedo:facts' %}">Interesting Facts </a>
                                <a class="dropdown-item" href="{% url 'wedo:statistics' %}">Data and statistics </a>
                                <a class="dropdown-item" href="{% url 'wedo:publications' %}">Recent Publications </a>
                            </div>
                        </div>
                    </li>
                    <li class="nav-item d-flex">
                        <form action="{% url 'set_language' %}" method="post">{% csrf_token %}
                            <input name="next" type="hidden" value="{{ redirect_to }}">
                            <select name="language" onchange="this.form.submit()" class="lang-select">
                                {% get_current_language as LANGUAGE_CODE %}
                                {% get_available_languages as LANGUAGES %}
                                {% get_language_info_list for LANGUAGES as languages %}

                                {% for language in languages %}
                                    <option value="{{ language.code }}" {% if language.code == LANGUAGE_CODE %} selected{% endif %}>
                                        {{ language.name_local }} ({{ language.code }})
                                    </option>
                                {% endfor %}

                            </select>
                        </form>
                    </li>
                </ul>
            </div>
        </nav>
    </div>
</div>
<!-- subnavbar -->